= Advent of Code Runner

Simple Java input parser for the https://adventofcode.com/[Advent of Code] challenges.

== Installation

This project requires **Java 11** or higher. If you still on a lower Java version, maybe it's a good time to consider
using something such https://github.com/jenv/jenv[jenv] that allows you to easily change your Java environment :).

. Clone this project
. Execute
+
----
./gradlew publishToMavenLocal
----
. Add the following dependency to your project's `build.gradle`
+
----
implementation 'com.perapoch.aoc:aoc-runner:+'
----
Note: you will need `mavenLocal()` added in your `repositories {}`.
. That's it!

== Usage

The only *requirement* to use `aoc-runner` is that you have a method annotated with the `@Input` annotation and a
single argument of any supported type (see the list below).

After invoking the `ChallengeRunner::run` the input file you specified as `source` will be parsed and injected to your
`@Input` annotated method.

Example:
[source, java]
----
package com.perapoch.aoc.day1;

public class AoCDay1 {

    @Input(source = "input.txt")
    public void run(List<Integer> input) {
        // solve the challenge
    }

    public static void main() {
        ChallengeRunner.run(AoCDay1.class);
    }
}
----

Once the `main` method is executed, the `ChallengeRunner` will look for a file named `input1.txt` in a *resource* folder
under the same package structure.

----
src
|-- main
    |-- java
    |   |-- com.perapoch.aoc.day1
    |       |-- AoCDay1.java
    |
    |-- resources
    |   |-- com.perapoch.aoc.day1
    |       |-- input1.txt
----

`ChallengeRunner` will automatically *parse* the file's content to create a new `List<Integer>` and call the `run`
method on the `AoCDay1` class with it.

=== Supported argument types

Supported argument types are:

* *Primitive types*: `int, long, char, float, double`
* *Boxed primitive types*: `Integer, Long, Character, Float, Double`
* *Custom*: yes, you can define your own type. See the <<README.adoc#Advanced usage,Advanced usage>> section for more info.
* `String`
* `List<T>` where `T` is any of the boxed primitive types, `String` or a custom type. Example: `List<Integer>`.
* `List<List<T>>`: where `T` is any of the boxed primitive types, `String` or a custom type. Example: `List<List<Integer>>`.

=== Supported file formats

Input files can have input in any of the following formats and contain any of the supported types listed above:

* Single element
+
----
1990
----
* Multiline elements
+
----
a
b
c
d
----
* Delimited list of elements
+
----
1,2,3,4
----
* Multiline delimited list of elements
+
----
x = 4
y = 9
z = x + y
----

Delimited lists are supported through the `splitBy` parameter in the `@Input` annotation. Example:
[source, Java]
----
@Input(source = "delimited_ints.txt", splitBy = ",")
public void run(List<Integer> input) {
    System.out.println(input); // will print [1,2,3,4]
}
----

=== Advanced usage

For most of the challenges any of the types described above should be enough. However, there are times were using your
own custom type can improve your code readability. To do that, you can use the `@CustomParser` annotation.

[source, java]
----
@CustomParser()
public Code parse(String line) {
    String[] parts = line.split("#");
    return new Code(parts[0], parts[1]);
}

@Input()
public void run(List<Code> input) {
    // solve the challenge
}
----

As it can be deducted by the example above, using the `@CustomParser` annotation will set up a new parser that converts an input line
to the custom type specified by the return type.
